# Goal
float32 target_force_grams
float32 tolerance_grams      # Force error tolerance
float32 settle_time_sec      # How long it must stay within tolerance
float32 timeout_sec          # Set to <= 0 for infinite timeout
uint8   control_strategy     # 0 = PID, 1 = ADMITTANCE
---
# Result
bool    success
uint8   final_state
float32 final_avg_force_grams
string  message
---
# Feedback
float32 actual_target_force_grams
float32 current_avg_force_grams
float32 force_error_grams
uint8   current_state